pipeline:
  identifier: Build_employee_harness_ui_1715952655312
  name: Build employee-harness-ui
  orgIdentifier: default
  projectIdentifier: employee
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: employee_ui
        repoName: employee-harness-ui
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: false
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18.14.2
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                      export CHROME_BIN=/usr/bin/chromium
                      npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
