pipeline:
  identifier: Build_employee_harness_ui_1715952655312
  name: Build employee-harness-ui
  orgIdentifier: default
  projectIdentifier: employee
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: employee_ui
        repoName: employee-harness-ui
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: false
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18.14.2
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - parallel:
        - stage:
            name: execute testcases
            identifier: execute_testcases
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run test cases
                      identifier: Run_test_cases
                      spec:
                        shell: Sh
                        command: npm test -- --watch=false --browsers=ChromeHeadless
        - stage:
            name: statusCheck
            identifier: statusCheck
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: echo "checking the status"
            when:
              pipelineStatus: Failure
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: Abort
