pipeline:
  identifier: Build_employee_harness_ui_1715952655312
  name: Build employee-harness-ui
  orgIdentifier: default
  projectIdentifier: employee
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: employee_ui
        repoName: employee-harness-ui
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: false
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18.14.2
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                  description: building application and running test cases
              - step:
                  type: Run
                  name: Test cases
                  identifier: Test_cases
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18.14.2
                    shell: Sh
                    command: |-
                      #!/bin/bash
                      # from https://chromium.woolyss.com/
                      # and https://gist.github.com/addyosmani/5336747
                      # and https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
                      apt-get update
                      apt-get install software-properties-common
                      add-apt-repository ppa:canonical-chromium-builds/stage
                      apt-get update
                      apt-get install chromium-browser 
                      chromium-browser --headless --no-sandbox http://example.org/

                      npm test -- --watch=false --browsers=ChromeHeadless
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Abort
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
